### PR TITLE
Dotty

### PR DESCRIPTION
**Pull request by jodersky**
Changes to the build and tests to cross-build against Dotty

### CODE REVIEW

**Review by anatoliykmetyuk — APPROVED** [review]
@jodersky could you update the Dotty version?

**Comment by jodersky** [comment]
Done

**Review by anatoliykmetyuk — APPROVED** [review]
Thanks @jodersky!
@lihaoyi can you review this? Or else could you add me to the repo so that I can manage these Dotty-related PRs?

**Comment by lihaoyi** [comment]
@anatoliykmetyuk gave you commit access

**Pull request merged**
